concurrency:
  group: ${{ github.ref }}-changeset-check
  cancel-in-progress: true
run-name: changeset-check
on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  changeset-check:
    if: github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          fetch-depth: 0

      - name: Check for changeset
        run: pnpm changeset status --since=origin/main
