concurrency:
  group: ${{ github.ref }}-lint
  cancel-in-progress: true
run-name: lint
on:
  push:
    branches-ignore:
      - main
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint code
        run: pnpm lint
